- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: Disable nodejs module
    ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y
  
  - name: Install nodejs 18
    ansible.builtin.dnf:
      name: nodejs
      state: present 
  - name: Add roboshop user
    ansible.builtin.user:
      name: roboshop
  
  - name: Create app directory
    ansible.builtin.file:
      path: /app/
      state: directory
  - name: Download from URL
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
  - name: Extract Catalogue.zip 
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
    

