- name: user
  hosts: user
  become: yes
  tasks:
  - name: Disable nodejs module
    ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y
  
  - name: Install nodejs 18
    ansible.builtin.dnf:
      name: nodejs
      state: present 
  - name: Add roboshop user
    ansible.builtin.user:
      name: roboshop
    
  - name: Remove /app old directory
    ansible.builtin.file:
      path: /app
      state: absent
  
  - name: Create app directory
    ansible.builtin.file:
      path: /app/
      state: directory
  - name: Download from URL
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp
  - name: Extract user.zip 
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
  
  - name: Install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app
  - name: create user.service file
    ansible.builtin.copy:
      src: /home/centos/roboshop-ansible/user.service
      dest: /etc/systemd/system/user.service

  - name: Daemon-reload
    ansible.builtin.systemd_service:
      daemon_reload: true
      # state: restarted    

  - name: Copy Mongodb repo to yum repos directory
    ansible.builtin.copy:
      src: /home/centos/roboshop-ansible/mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present
  - name: get the categories count
    ansible.builtin.command: mongo --host mongodb.ganeshthommandru.online --quiet --eval 'db = db.getSiblingDB("users"); db.products.count()'
    register: users

  - name: print the count
    ansible.builtin.debug:
      msg: "Product Count: {{users}}"

  - name: Load user data  
    ansible.builtin.command: mongo --host mongodb.ganeshthommandru.online < /app/schema/user.js
    when: product_count.stdout == "0" # Keep doubel quotes

  - name: Start and enable user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes